/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AllUsersRouteImport } from './routes/all-users'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesIndexRouteImport } from './routes/examples/index'
import { Route as ExamplesIdRouteImport } from './routes/examples/$id'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'

const AllUsersRoute = AllUsersRouteImport.update({
  id: '/all-users',
  path: '/all-users',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/examples/',
  path: '/examples/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIdRoute = ExamplesIdRouteImport.update({
  id: '/examples/$id',
  path: '/examples/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-users': typeof AllUsersRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/examples/$id': typeof ExamplesIdRoute
  '/examples': typeof ExamplesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-users': typeof AllUsersRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/examples/$id': typeof ExamplesIdRoute
  '/examples': typeof ExamplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-users': typeof AllUsersRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/examples/$id': typeof ExamplesIdRoute
  '/examples/': typeof ExamplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-users'
    | '/auth/sign-up'
    | '/examples/$id'
    | '/examples'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/all-users' | '/auth/sign-up' | '/examples/$id' | '/examples'
  id:
    | '__root__'
    | '/'
    | '/all-users'
    | '/auth/sign-up'
    | '/examples/$id'
    | '/examples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllUsersRoute: typeof AllUsersRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ExamplesIdRoute: typeof ExamplesIdRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/all-users': {
      id: '/all-users'
      path: '/all-users'
      fullPath: '/all-users'
      preLoaderRoute: typeof AllUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/': {
      id: '/examples/'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/$id': {
      id: '/examples/$id'
      path: '/examples/$id'
      fullPath: '/examples/$id'
      preLoaderRoute: typeof ExamplesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllUsersRoute: AllUsersRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ExamplesIdRoute: ExamplesIdRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
